Imports System.Text
Imports OGA.BI
Imports OGA.DA.Base
Public Class GoldenCrossDA
    Inherits DataBaseAcess

    Public Function Selectゴールデンクロス() As (DBResult, List(Of ゴールデンクロス))
        Dim stbSql As New StringBuilder
        stbSql.Append(" WITH BASE AS ( ")
        stbSql.Append("  SELECT  ")
        stbSql.Append("         証券コード ")
        stbSql.Append("       , 企業名 ")
        stbSql.Append("       , 日付 ")
        stbSql.Append("       , 出来高 ")
        stbSql.Append("       , 調整後終値 ")
        stbSql.Append("       , CASE WHEN 移動平均5件数  = 5  THEN 移動平均5  ELSE NULL END AS 移動平均5 ")
        stbSql.Append("       , CASE WHEN 移動平均25件数 = 25 THEN 移動平均25 ELSE NULL END AS 移動平均25 ")
        stbSql.Append("       , CASE WHEN 移動平均75件数 = 75 THEN 移動平均75 ELSE NULL END AS 移動平均75 ")
        stbSql.Append("   FROM  ")
        stbSql.Append("        (  ")
        stbSql.Append("         SELECT  ")
        stbSql.Append("                証券コード ")
        stbSql.Append("              , 企業名 ")
        stbSql.Append("              , 日付 ")
        stbSql.Append("              , 出来高 ")
        stbSql.Append("              , 調整後終値 ")
        stbSql.Append("              , AVG(調整後終値)   OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 4  PRECEDING AND CURRENT ROW) AS 移動平均5 ")
        stbSql.Append("              , COUNT(調整後終値) OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 4  PRECEDING AND CURRENT ROW) AS 移動平均5件数 ")
        stbSql.Append("              , AVG(調整後終値)   OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 24 PRECEDING AND CURRENT ROW) AS 移動平均25 ")
        stbSql.Append("              , COUNT(調整後終値) OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 24 PRECEDING AND CURRENT ROW) AS 移動平均25件数 ")
        stbSql.Append("              , AVG(調整後終値)   OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 74 PRECEDING AND CURRENT ROW) AS 移動平均75 ")
        stbSql.Append("              , COUNT(調整後終値) OVER(PARTITION BY 証券コード ORDER BY 日付 ROWS BETWEEN 74 PRECEDING AND CURRENT ROW) AS 移動平均75件数 ")
        stbSql.Append("           FROM 株価 ")
        stbSql.Append("        ) AS TBL  ")
        stbSql.Append(" ) ")
        stbSql.Append(" SELECT  ")
        stbSql.Append("        証券コード ")
        stbSql.Append("      , 企業名 ")
        stbSql.Append("      , 日付 ")
        stbSql.Append("      , 調整後終値 ")
        stbSql.Append("   FROM  ")
        stbSql.Append("        ( ")
        stbSql.Append("         SELECT  ")
        stbSql.Append("                証券コード ")
        stbSql.Append("              , 企業名 ")
        stbSql.Append("              , 日付 ")
        stbSql.Append("              , 出来高 ")
        stbSql.Append("              , 調整後終値 ")
        stbSql.Append("              , LAG(調整後終値,1,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 調整後終値_1 ")
        stbSql.Append("              , LAG(調整後終値,2,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 調整後終値_2 ")
        stbSql.Append("              , LAG(調整後終値,3,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 調整後終値_3 ")
        stbSql.Append("              , LAG(調整後終値,4,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 調整後終値_4 ")
        stbSql.Append("              , LAG(調整後終値,5,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 調整後終値_5 ")
        stbSql.Append("              , 移動平均5 ")
        stbSql.Append("              , LAG(移動平均5,1,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均5_1 ")
        stbSql.Append("              , LAG(移動平均5,2,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均5_2 ")
        stbSql.Append("              , LAG(移動平均5,3,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均5_3 ")
        stbSql.Append("              , LAG(移動平均5,4,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均5_4 ")
        stbSql.Append("              , LAG(移動平均5,5,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均5_5 ")
        stbSql.Append("              , 移動平均25 ")
        stbSql.Append("              , LAG(移動平均25,1,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均25_1 ")
        stbSql.Append("              , LAG(移動平均25,2,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均25_2 ")
        stbSql.Append("              , LAG(移動平均25,3,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均25_3 ")
        stbSql.Append("              , LAG(移動平均25,4,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均25_4 ")
        stbSql.Append("              , LAG(移動平均25,5,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均25_5 ")
        stbSql.Append("              , 移動平均75 ")
        stbSql.Append("              , LAG(移動平均75,1,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均75_1 ")
        stbSql.Append("              , LAG(移動平均75,2,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均75_2 ")
        stbSql.Append("              , LAG(移動平均75,3,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均75_3 ")
        stbSql.Append("              , LAG(移動平均75,4,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均75_4 ")
        stbSql.Append("              , LAG(移動平均75,5,NULL) OVER(PARTITION BY 証券コード ORDER BY 日付) AS 移動平均75_5 ")
        stbSql.Append("           FROM BASE ")
        stbSql.Append("        ) TBL ")
        stbSql.Append("    WHERE 1 = 1 ")
        'stbSql.Append("          移動平均75_5 < 移動平均75_4 ")
        'stbSql.Append("      AND 移動平均75_4 < 移動平均75_3 ")
        'stbSql.Append("      AND 移動平均75_3 < 移動平均75_2 ")
        'stbSql.Append("      AND 移動平均75_2 < 移動平均75_1 ")
        'stbSql.Append("      AND 移動平均75_1 < 移動平均75 ")
        stbSql.Append("      AND (移動平均75_5 > 調整後終値_5 ")
        stbSql.Append("      AND 移動平均75_4 > 調整後終値_4 ")
        stbSql.Append("      AND 移動平均75_3 > 調整後終値_3 ")
        stbSql.Append("      AND 移動平均75_2 > 調整後終値_2 ")
        stbSql.Append("      AND 移動平均75_1 > 調整後終値_1 ")
        stbSql.Append("      AND 移動平均75   < 調整後終値 ) ")
        stbSql.Append("      OR  (移動平均75_5 > 移動平均25_5 ")
        stbSql.Append("      AND 移動平均75_4 > 移動平均25_4 ")
        stbSql.Append("      AND 移動平均75_3 > 移動平均25_3 ")
        stbSql.Append("      AND 移動平均75_2 > 移動平均25_2 ")
        stbSql.Append("      AND 移動平均75_1 > 移動平均25_1 ")
        stbSql.Append("      AND 移動平均75   < 移動平均25 ) ")

        Return Me.DBSelect(Of ゴールデンクロス)(stbSql.ToString())
    End Function

End Class
